# .streamlit/config.toml
# [theme]
# primaryColor = "#F63366"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
# font = "sans serif"


[server]
headless = true
port = 8501
enableCORS = false
debug = true

[logger]
level = "debug"


[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true
installTracer = true

[client]
toolbarMode = "auto"
showErrorDetails = true
